### ISSUE TITLE
Unknown table specified in objecttable field when logging an aevent

### ISSUE THREAD

**Issue by juacas** [juacas/moodle-mod_scavenger#1]
En el script editroad.php ha aparecido este error usando Moodle 2.9.5.  Está relacionado con el registro del evento, no he podido investigar su causa:

Unknown table specified in objecttable field
•	line 673 of \lib\classes\event\base.php: call to debugging()
•	line 695 of \lib\classes\event\base.php: call to core\event\base->validate_before_trigger()
•	line 103 of \mod\scavengerhunt\editroad.php: call to core\event\base->trigger()

**Comment by huorwhisp** [comment]
Solved
