### ISSUE TITLE
Error writing to database

### ISSUE THREAD

**Issue by juacas** [juacas/moodle-mod_scavenger#4]
When saving the scenario a database error is raised.

Debuginfo: "FUNCTION moodle2.ST_GeomFromText does not exist UPDATE mdl_scavengerhunt_riddles SET num_riddle=(?), geom = ST_GeomFromText((?)), timemodified=(?) WHERE mdl_scavengerhunt_riddles.id = (?) [array ( 0 => 1, 1 => 'MULTIPOLYGON(((-4,7061389777809 41,662495870578,-4,7060209605843 41,662549973349,-4,7059662686661 41,662488356301,-4,7060888169689 41,662439055419,-4,7061389777809 41,662495870578)))', 2 => 1460108254, 3 => 1, )] Error code: dmlwriteexception"

Server: http://itastdevserver.tel.uva.es/moodle2/mod/scavengerhunt/edit.php?id=363
MySQL:  5.5.47-0ubuntu0.12.04.1

Hint: If the database is not supported the module should be fully disabled.

**Comment by huorwhisp** [comment]
Has actualizado el módulo?

**Comment by juacas** [comment]
MySQL 5.5 uses GeomFromText. It hasn't ST_GeomFromText synonym.
https://dev.mysql.com/doc/refman/5.5/en/gis-wkt-functions.html

To check mySQL version: SHOW VARIABLES like "version";
version: 5.5.47-0ubuntu0.12.04.1

**Comment by juacas** [comment]
Solved in rev 04e493ac61320aef3a816c8d5507e9a377fecf43
